### ISSUE TITLE
the tutorial part probably needs an overhaul

### ISSUE THREAD

**Issue by ls-sudo** [Kurento/kurento#19]
In the tutorial documentation([doc-kurento](https://github.com/Kurento/doc-kurento) or https://doc-kurento.readthedocs.io/en/6.10.0/tutorials/java/tutorial-helloworld.html), links to code snippets on github are not working, and many codes shown in the tutorials are different from the actual ones provided in tutorial folder of the kurento project([kurento](https://github.com/Kurento/kurento)).

**Comment by j1elo** [comment]
The tutorials do need a good overhaul indeed, for things like getting rid of all uses of kurento-utils-js, and fixing some presentation issues like embedded image links in the application pages...

but in this specific case I noticed you're looking at docs of Kurento 6.10.0 which is from 2019, so I'd recommend to start by checking the latest version of the docs, which probably have lots of small issues corrected:

https://doc-kurento.readthedocs.io/en/latest/tutorials/java/tutorial-helloworld.html
